- hosts: all
  tasks:
  - name: docker
    yum_repository:
           description: Docker Setup
           name: Docker
           baseurl:  https://download.docker.com/linux/centos/7/x86_64/stable
           gpgcheck: no

  - package:
           name: "docker-ce-18.09.1-3.el7.x86_64"
           state: present

  - name: initialising  docker service
    service:
           name: "docker"
           state: started
           enabled: yes
  - name: installng docker sdk
    command: pip3 install docker

  - name: Create directory
    file:
          path: /workspace
          state: directory

  - name: Copying the webpages to the directory
    copy:
          src: "home.html"
          dest: "/workspace"

  - name: Creating the container & exposed the port
    docker_container:
          name: web
          image: httpd
          state: started
          exposed_ports:
          - "80"
          ports:
          - "8081:80"
          volumes:
          - /workspace:/usr/local/apache2/htdocs
~
